compiler_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "web_compiler"
urlpatterns = [
    path("", views.index, name="index"),
    path("file/<int:file_id>/", views.open_file, name="open_file"),
    path("catalog/<int:catalog_id>/", views.open_catalog, name="open_catalog"),
    path("add_catalog/<int:catalog_id>/", views.add_catalog, name="add_catalog"),
    path("add_file/<int:catalog_id>/", views.add_file, name="add_file"),
    path(
        "delete_catalog/<int:catalog_id>/", views.delete_catalog, name="delete_catalog"
    ),
    path("delete_file/<int:file_id>/", views.delete_file, name="delete_file"),
    path("compiled_file/<int:file_id>/", views.compiled_file, name="compiled_file"),
    path(
        "download_compiled_file/<int:file_id>/",
        views.download_compiled_file,
        name="download_compiled_file",
    ),
    path("set_compile_options/", views.set_compile_options, name="set_compile_options"),
    path("login/", LoginView.as_view(next_page="/compiler/"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/compiler/login/"), name="logout"),
    path("add_section/<int:file_id>/", views.add_section, name="add_section"),
]

web_compiler/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path("compiler/", include("compiler_app.urls")),
    path("admin/", admin.site.urls),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    path(
        "",
        RedirectView.as_view(url="compiler"),
    ),
]

compiler_app/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator


class Named(models.Model):
    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Container(Named):
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(default=now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    availability_change_date = models.DateTimeField(blank=True, null=True)
    content_change_date = models.DateTimeField(default=now)
    holder = models.ForeignKey(
        "Catalog", blank=True, null=True, on_delete=models.CASCADE
    )

    class Meta:
        abstract = True


class Catalog(Container):
    pass


class File(Container):
    actual_file = models.FileField(
        upload_to="files/", validators=[FileExtensionValidator(["c"])]
    )


class SectionType(models.Model):
    name = models.CharField(max_length=30, blank=True)
    type = models.CharField(max_length=200, unique=True)
    css_class = models.CharField(max_length=30)

    def __str__(self):
        return self.type


class SectionStatus(models.Model):
    status = models.CharField(max_length=30)

    def __str__(self):
        return self.status


class FileSection(models.Model):
    name = models.CharField(max_length=30, blank=True)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(default=now)
    section_start = models.PositiveIntegerField()
    section_end = models.PositiveIntegerField()
    section_type = models.ForeignKey(SectionType, on_delete=models.CASCADE)
    section_status = models.ForeignKey(
        SectionStatus, on_delete=models.CASCADE, default=4
    )
    status_data = models.TextField(blank=True)
    section_data = models.TextField()
    section_of = models.ForeignKey(File, on_delete=models.CASCADE)

compiler_app/forms.py
from django import forms
from .models import FileSection, Catalog, File


class NewCatalogForm(forms.ModelForm):
    class Meta:
        model = Catalog
        fields = ["name"]
        labels = {"name": ""}


class AddSectionForm(forms.ModelForm):
    class Meta:
        model = FileSection
        fields = ["section_start", "section_end", "section_type", "section_of"]
        widgets = {
            "section_start": forms.HiddenInput(),
            "section_end": forms.HiddenInput(),
            "section_type": forms.HiddenInput(),
            "section_of": forms.HiddenInput(),
        }


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["actual_file"]
        widgets = {
            "actual_file": forms.FileInput(
                attrs={"class": "hidden", "onChange": "sendForm(form);"}
            ),
        }
        labels = {"actual_file": ""}


class StandardForm(forms.Form):
    STANDARDS = [("--std-c89", "C89"), ("--std-c99", "C99"), ("--std-c11", "C11")]
    standard = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"onChange": "sendForm(form);"}),
        choices=STANDARDS,
        label=False,
    )


class OptimizationsForm(forms.Form):
    OPTIMIZATIONS = [
        ("--nogcse", "No gcse"),
        ("--noinvariant", "No invariant"),
        ("--noinduction", "No induction"),
    ]
    optimizations = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"onChange": "sendForm(form);"}),
        choices=OPTIMIZATIONS,
        label=False,
        required=False,
    )


class ProcessorForm(forms.Form):
    PROCESSORS = [("-mmcs51", "MCS51"), ("-mz80", "Z80"), ("-mstm8", "STM8")]
    processor = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"onChange": "sendForm(form);"}),
        choices=PROCESSORS,
        label=False,
    )


class Options(forms.Form):
    pass


class OptionsMCS51Form(Options):
    OPTIONS = [
        ("--model-large", "Model large"),
        ("--model-medium", "Model medium"),
        ("--model-small", "Model small"),
    ]
    proc_option1 = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"onChange": "sendForm(form);"}),
        choices=OPTIONS,
        label=False,
    )


class OptionsZ80Form(Options):
    OPTIONS = [
        ("--callee-saves-bc", "Callee saves bc"),
        ("--oldralloc", "Oldralloc"),
        ("--emit-externs", "Emit externs"),
    ]
    proc_option1 = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"onChange": "sendForm(form);"}),
        choices=OPTIONS,
        label=False,
        required=False,
    )


class OptionsSTM8Form(Options):
    OPTIONS1 = [("--model-large", "Model large"), ("--model-medium", "Model medium")]
    OPTIONS2 = [("--out-fmt-elf", "Out fmt elf")]
    proc_option1 = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"onChange": "sendForm(form);"}),
        choices=OPTIONS1,
        label=False,
    )
    proc_option2 = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"onChange": "sendForm(form);"}),
        choices=OPTIONS2,
        label=False,
        required=False,
    )

compiler_app/views.py
from typing import Any, Dict
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.utils.timezone import now
from django.urls import reverse
from django.http import HttpResponseRedirect, FileResponse
from django.contrib.auth.decorators import login_required
from os.path import splitext, split
import subprocess
import re

from .models import Catalog, File, FileSection, SectionType, SectionStatus
from .forms import (
    NewCatalogForm,
    AddSectionForm,
    StandardForm,
    OptimizationsForm,
    ProcessorForm,
    OptionsMCS51Form,
    OptionsZ80Form,
    OptionsSTM8Form,
    Options,
    UploadFileForm,
)


def get_basic_context(user, session):
    basic_context = {
        "catalogs": Catalog.objects.all().filter(owner=user, holder=None),
        "files": File.objects.all().filter(owner=user, holder=None),
        "newCatalogForm": NewCatalogForm(),
        "standardForm": StandardForm(initial=session.get("standard", None)),
        "optimizationsForm": OptimizationsForm(
            initial=session.get("optimizations", None)
        ),
        "processorForm": ProcessorForm(initial=session.get("processor", None)),
        "optionsMCS51Form": OptionsMCS51Form(initial=session.get("proc_option1", None)),
        "optionsZ80Form": OptionsZ80Form(initial=session.get("proc_option1", None)),
        "optionsSTM8Form": OptionsSTM8Form(initial=session.get("proc_option1", None)),
        "uploadFileForm": UploadFileForm(),
    }
    return basic_context


@login_required(login_url="/compiler/login")
def index(request):
    return render(
        request, "index.html", get_basic_context(request.user, request.session)
    )


class LinedFileSection:
    pass


class NumedLine:
    pass


def get_lined_sections(file_sections):
    result = list()
    line_num = 1

    for section in file_sections:
        result.append(LinedFileSection())
        result[-1].lines = list()
        result[-1].css_class = section.section_type.css_class
        result[-1].title = section.section_type.name
        for line in section.section_data.splitlines():
            result[-1].lines.append(NumedLine())
            result[-1].lines[-1].data = line + "\n"
            result[-1].lines[-1].num = line_num
            line_num += 1

    return result


def open_file_context(file, request):
    context = get_basic_context(request.user, request.session)
    context["file_content"] = get_lined_sections(
        file.filesection_set.all().order_by("section_start")
    )
    context["current_file"] = file
    context["current_catalog"] = file.holder
    context["addSectionForm"] = AddSectionForm(initial={"section_of": file})

    return context


@login_required(login_url="/compiler/login")
def open_file(request, file_id):
    current_file = get_object_or_404(File, pk=file_id, owner=request.user)
    context = open_file_context(current_file, request)

    return render(request, "index.html", context)


@login_required(login_url="/compiler/login")
def open_catalog(request, catalog_id):
    current_catalog = get_object_or_404(Catalog, pk=catalog_id, owner=request.user)
    context = get_basic_context(request.user, request.session)
    context["current_catalog"] = current_catalog
    return render(request, "index.html", context)


def update_content_change_date(catalog):
    catalog.content_change_date = now()
    catalog.save()
    if catalog.holder:
        update_content_change_date(catalog.holder)


@login_required(login_url="/compiler/login")
def add_catalog(request, catalog_id):
    if request.method == "POST":
        form = NewCatalogForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            holder = Catalog.objects.filter(pk=catalog_id, owner=request.user).first()
            catalog = Catalog(name=name, holder=holder, owner=request.user)
            if holder:
                update_content_change_date(holder)
            catalog.save()
            return HttpResponseRedirect(
                reverse("web_compiler:open_catalog", args=(catalog.id,))
            )

    context = get_basic_context(request.user, request.session)
    context["add_to_catalog_id"] = catalog_id
    context["current_catalog"] = Catalog.objects.filter(
        pk=catalog_id, owner=request.user
    ).first()
    return render(request, "index.html", context)


def find_section_type(line):
    if re.match("^[ \t]*#", line):
        return SectionType.objects.get(type="Compiler directive")

    if re.match("^[ \t]*//", line):
        return SectionType.objects.get(type="Comment")

    return SectionType.objects.get(type="Other")


def parse_file(file):
    with file.actual_file.open("r") as f:
        currentSection = None
        currentLine = 0
        for line in f:
            type = find_section_type(line)
            if currentSection and currentSection.section_type == type:
                currentSection.section_data += line
                currentSection.section_end = currentLine
            else:
                if currentSection:
                    currentSection.save()
                currentSection = FileSection(
                    section_start=currentLine,
                    section_end=currentLine,
                    section_type=type,
                    section_data=line,
                    section_of=file,
                )
            currentLine += 1
        if currentSection:
            currentSection.save()


@login_required(login_url="/compiler/login")
def add_file(request, catalog_id):
    form = UploadFileForm(request.POST, request.FILES)
    if form.is_valid():
        name = request.FILES["actual_file"].name
        holder = Catalog.objects.filter(pk=catalog_id, owner=request.user).first()
        if holder:
            update_content_change_date(holder)
        file = File(
            name=name,
            holder=holder,
            owner=request.user,
            actual_file=request.FILES["actual_file"],
        )
        file.save()
        parse_file(file)
        return HttpResponseRedirect(reverse("web_compiler:open_file", args=(file.id,)))

    next = request.POST.get("next", "/compiler")

    return HttpResponseRedirect(next)


@login_required(login_url="/compiler/login")
def delete_file(request, file_id):
    file = get_object_or_404(File, pk=file_id, owner=request.user)
    file.available = False
    file.availability_change_date = now()
    file.save()
    if file.holder:
        update_content_change_date(file.holder)
        return HttpResponseRedirect(
            reverse("web_compiler:open_catalog", args=(file.holder.id,))
        )
    return HttpResponseRedirect(reverse("web_compiler:index"))


def change_availability(catalog):
    catalog.available = False
    catalog.availability_change_date = now()

    for file in catalog.file_set.all():
        file.available = False
        file.availability_change_date = now()
        file.save()

    for next_catalog in catalog.catalog_set.all():
        change_availability(next_catalog)

    catalog.save()


@login_required(login_url="/compiler/login")
def delete_catalog(request, catalog_id):
    catalog = get_object_or_404(Catalog, pk=catalog_id, owner=request.user)
    change_availability(catalog)
    if catalog.holder:
        update_content_change_date(catalog.holder)
        return HttpResponseRedirect(
            reverse("web_compiler:open_catalog", args=(catalog.holder.id,))
        )
    return HttpResponseRedirect(reverse("web_compiler:index"))


def add_to_list(my_list, val):
    if val:
        to_add = list(val.values())
        for el in to_add:
            if type(el) is list:
                my_list.extend(el)
            else:
                my_list.append(el)


class CompiledFileSection:
    pass


class ContentPart:
    pass


@login_required(login_url="/compiler/login")
def compiled_file(request, file_id):
    file = get_object_or_404(File, pk=file_id, owner=request.user)
    open("compiled.asm", "w+").close()
    run_list = ["sdcc", "-S", "-o", "compiled.asm"]

    add_to_list(run_list, request.session.get("standard", None))
    add_to_list(run_list, request.session.get("optimizations", None))
    add_to_list(run_list, request.session.get("processor", None))
    add_to_list(run_list, request.session.get("proc_option1", None))

    run_list.append(file.actual_file.path)
    run_out = subprocess.run(run_list, capture_output=True, text=True)
    context = open_file_context(file, request)

    result = list()
    if run_out.returncode != 0:
        result.append(CompiledFileSection())
        result[-1].content = run_out.stderr
        f = open("compiled.asm", "w+")
        f.write(run_out.stderr)
        f.close()
        result[-1].css_class = "section__error"
        result[-1].rest = ""
    else:
        f = open("compiled.asm", "r")
        compiled_file_content = f.readlines()
        f.close()

        is_header = False
        id = 0
        for line in compiled_file_content:
            if re.match("^;-", line):
                if is_header:
                    result[-1].content += line
                    is_header = False
                    result.append(CompiledFileSection())
                    result[-1].content = ""
                    result[-1].css_class = "section__content"
                    result[-1].rest = f"id=header-{id}"
                    id += 1
                else:
                    result.append(CompiledFileSection())
                    result[-1].content = line
                    result[-1].css_class = "section__header"
                    result[-1].rest = f"onclick=hideHeader('#header-{id}')"
                    is_header = True
            else:
                result[-1].content += line

    for res in result:
        res.content = re.sub(
            r"\.c:\s*(\d+)(.*)",
            r".c:<div class='help' id='help\1' onclick='highlightLine(\1)'>\1\2</div>",
            res.content,
        )

compiler_app/templates/base_generic.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <title>Kompilator</title>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'compiler_app/login.css' %}?version=15">

  {% block head%}
  {% endblock %}

</head>

<body>
  {% block body %}
  {% endblock %}
</body>

</html>

compiler_app/templates/compiled_code.html
<code class="code__code">
{% for section in compiled_file_content %}<div class="section, {{ section.css_class }}" {{ section.rest }}>{{ section.content|safe }}</div>{% endfor %}
</code>

compiler_app/templates/delete.html
{% if current_file %}
    <li>
        <form class="menu__button" action="{% url 'web_compiler:delete_file' current_file.id %}" method="post" onsubmit="sendPost(event, this)">
            {% csrf_token %}
            <input class="menu__button" type="submit" value="Usuń plik">
        </form>
    </li>
{% endif %}
{% if current_catalog %}  
    <li>
        <form class="menu__button" action="{% url 'web_compiler:delete_catalog' current_catalog.id %}" method="post" onsubmit="sendPost(event, this)">
            {% csrf_token %}
            <input class="menu__button" type="submit" value="Usuń katalog">
        </form>
    </li>
{% endif %}

compiler_app/templates/display_file.html
{% for section in file_content%}<div class={{ section.css_class }} title={{ section.title }}>{% include 'display_lines.html' %}</div>{% endfor %}

compiler_app/templates/display_lines.html
{% for line in section.lines %}<div class="line"><div class="numed-line" id="numed-{{ line.num }}" onclick="markLine({{ line.num }})">{{ line.num }}</div><div class="line-data" id="line-{{ line.num }}" tabindex='1'>{{ line.data }}</div></div>{% endfor %}

compiler_app/templates/file_tree.html
{% for catalog in catalogs%}
    {% if catalog.available %}
    <li>
        {% if current_catalog and current_catalog.id == catalog.id %}
        <a class="tree-node selected" onclick="changePage('{% url 'web_compiler:open_catalog' catalog.id %}')">&#128193; {{ catalog.name }}</a>
        {% else %}
        <a class="tree-node" onclick="changePage('{% url 'web_compiler:open_catalog' catalog.id %}')">&#128193; {{ catalog.name }}</a>
        {% endif %}
            <ul>
                {% if add_to_catalog_id == catalog.id %}
                    {% include "new_catalog.html" %}
                {% endif %}
                {% with catalogs=catalog.catalog_set.all files=catalog.file_set.all %}
                    {% include "file_tree.html" %}
                {% endwith %}
            </ul>
        </details>
    </li>
    {% endif %}
{% endfor %}

{% for file in files%}
    {% if file.available %}
    <li>
        {% if current_file and current_file.id == file.id %}
        <a class="tree-node selected" onclick="changePage('{% url 'web_compiler:open_file' file.id %}')">{{ file.name }}</a>
        {% else %}
        <a class="tree-node" onclick="changePage('{% url 'web_compiler:open_file' file.id %}')">{{ file.name }}</a>
        {% endif %}
    </li>
    {% endif %}
{% endfor %}

compiler_app/templates/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
  <title>Kompilator</title>

  <link rel="stylesheet" href="{% static 'compiler_app/style.css' %}?version=18">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="{% static 'compiler_app/scripts.js' %}?version=5"></script>

  <meta charset="UTF-8">
</head>

<body>
  <div class="grid" id="grid">
    <div class="grid__menu">
      <a class="menu__burger burger" href="#menu-navbar">&#9776;</a>
      <ul class="menu__menu-navbar navbar" id="menu-navbar">
        <li class="menu-navbar__item navbar-item">
          <a class="menu-navbar__link" href="#plik">Plik</a>
            <ul>
              <li>{% include "upload_file.html" %}</li>
              <li><a class="menu__button" onclick="changePage('{% url 'web_compiler:add_catalog' current_catalog.id|default:"0" %}')">Dodaj folder</a></li>
              {% if current_file %}
                <li><a class="menu__button" onclick="changePage('{% url 'web_compiler:compiled_file' current_file.id %}')">Kompiluj</a></li>
              {% endif %}
              {% if compiled_file_content %}
                <li><a class="menu__button" href="{% url 'web_compiler:download_compiled_file' current_file.id %}">Pobierz skompilowany plik</a></li>
              {% endif %}
            </ul>
        </li>
        <li class="menu-navbar__item navbar-item">
          <a class="menu-navbar__link" href="#edycja">Edycja</a>
            <ul>
              {% include "delete.html" %}
            </ul>
        </li>
        <li class="menu-navbar__item navbar-item">
          <a class="menu-navbar__link" href="#opcje">Opcje</a>
            <ul>
              {% if compiled_file_content %}
              <li><div class="menu__button" onclick="hideSections()">Schowaj wszystkie sekcje</div></li>
              <li><div class="menu__button" onclick="showSections()">Pokaż wszystkie sekcje</div></li>
              {% endif%}
              {% if user.is_authenticated %}
              <li><a class="menu__button" href="{% url 'web_compiler:logout' %}">Wyloguj</a></li>
              {% else %}
              <li><a class="menu__button" href="{% url 'web_compiler:login' %}">Zaloguj</a></li>
              {% endif %}
            </ul>
        </li>
        <li class="menu-navbar__item navbar-item">
          <a class="menu-navbar__link" href="#dodaj_sekcje">Dodaj sekcję</a>
          <ul>
            {% if current_file %}
            <form id="add-section-id" class="add-section" action="{% url 'web_compiler:add_section' current_file.id %}" method="post">
              {% csrf_token %}
              {{ addSectionForm }}
              <li><div class="menu__button" onclick="addSection(6)">Procedura</div></li>
              <li><div class="menu__button" onclick="addSection(5)">Komentarz</div></li>
              <li><div class="menu__button" onclick="addSection(4)">Dyrektywa</div></li>
              <li><div class="menu__button" onclick="addSection(3)">Deklaracja zmiennych</div></li>
              <li><div class="menu__button" onclick="addSection(2)">Wstawka assemblerowa</div></li>
              <li><div class="menu__button" onclick="addSection(1)">Inna</div></li>
            </form>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>

    <div class="grid__file-choose">
      <ul class="file-choose__tree">
        {% if add_to_catalog_id == 0 %}
          {% include "new_catalog.html" %}
        {% endif %}
        {% include "file_tree.html" %}
      </ul>
      <a class="file-choose__main" onclick="changePage('{% url 'web_compiler:index' %}')"></a>
    </div>

    <pre class="grid__program-code grid__other grid__code code__code">{% include 'display_file.html' %}</pre>

    <pre class="grid__code-fragment grid__other grid__code">{% include 'compiled_code.html' %}</pre>

    
    <div class="grid__tabs">
      <ul class="tabs__tabs-navbar navbar grid__other">
        <li class="tabs-navbar__item navbar-item">
          <a class="tabs-navbar__link" href="#tab1">STANDARD</a>
        </li>
        <li class="tabs-navbar__item navbar-item">
          <a class="tabs-navbar__link" href="#tab2">OPTYMALIZACJE</a>
        </li>
        <li class="tabs-navbar__item navbar-item">
          <a class="tabs-navbar__link" href="#tab3">PROCESOR</a>
        </li>
        <li class="tabs-navbar__item navbar-item">
          <a class="tabs-navbar__link" href="#tab4" on>ZALEŻNE</a>
        </li>
      </ul>

      <form class="tabs__tab-field grid__other" action="{% url 'web_compiler:set_compile_options' %}" method="post" onsubmit="sendPost(event,this)">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        {% include 'tabs.html' %}
      </form>
    </div>
  </div>
</body>

</html>

compiler_app/templates/mcs51_options.html
{{ optionsMCS51Form }}

compiler_app/templates/new_catalog.html
<form action="{% url 'web_compiler:add_catalog' current_catalog.id|default:"0" %}" method="post" onsubmit="sendPost(event,this)">
    {% csrf_token %}
    {{ newCatalogForm.as_table }}
    <input type="submit" value="Utwórz">
</form>

compiler_app/templates/stm8_options.html
{{ optionsSTM8Form }}

compiler_app/templates/tabs.html
  <div class="tab" id="tab1">
    {{ standardForm }}
  </div>
  <div class="tab" id="tab2">
    {{ optimizationsForm }}
  </div>
  <div class="tab" id="tab3">
    {{ processorForm }}
  </div>
  <div class="tab" id="tab4">
    {% if request.session.processor.processor == "-mmcs51" %} {% include 'mcs51_options.html' %} {% endif %}
    {% if request.session.processor.processor == "-mz80" %} {% include 'z80_options.html' %} {% endif %}
    {% if request.session.processor.processor == "-mstm8" %} {% include 'stm8_options.html' %} {% endif %}
  </div>

compiler_app/templates/upload_file.html
<form action="{% url 'web_compiler:add_file' current_catalog.id|default:"0" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <label class="menu__button" for="id_actual_file">
        {{ uploadFileForm }}
        Dodaj plik
    </label>
</form>

compiler_app/templates/z80_options.html
{{ optionsZ80Form }}